### ISSUE TITLE
bitsandbytes & accelerate errors on CPU usage

### ISSUE THREAD

**Issue by Mosharush** [ShmuelRonen/Hebrew-Mistral-7B-GUI#1]
Hey,
I tried to run it on my Mac M1 apple chip and got this error:
![Screenshot 2024-05-03 at 14 25 28](https://github.com/ShmuelRonen/Hebrew-Mistral-7B-GUI/assets/17269509/d147e73b-8f37-431e-b263-a3c56eabf820)

For setup, I convert the `bat` script to `bash`:
init_env.sh:
```
#!/bin/bash

# Check if virtual environment exists
if [ ! -d "venv" ]
then
    echo "Creating virtual environment..."
    python3 -m venv venv
    echo "Virtual environment created."
fi

# Activate the virtual environment
source venv/bin/activate

# Install requirements
echo "Installing requirements..."
pip install accelerate
pip install -i https://pypi.org/simple/ bitsandbytes
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt
echo "Requirements installed!"

# Run the Python script
python3 heb.py
```

**Comment by ShmuelRonen** [comment]
1. What is "fi" 
2. I don't have a Mac, so I won't be able to check the error.
3. Try to install manually step by step

**Comment by Mosharush** [comment]
1. `fi` it's like the close word of `if` scope in bash.
2. I checked also on Linux Ubuntu 22 in Cloud, step by step and the same error.

I am pretty sure it's something about CPU usage and not GPU,
Maybe specific Nvidia chip needed?

**Comment by ShmuelRonen** [comment]
I think that the best way 4 you is to use it on Google colab with this notepad: Hebrew-Mistral-7B.ipynb. It's works fine on T4 GPU there
